//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace LTrWebLibraryBTL.View.server
{


    public partial class ServerSideControl
    {

        /// <summary>
        /// UCQuanLyNguoiDung control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::LTrWebLibraryBTL.UserControl.WebUserControl1 UCQuanLyNguoiDung;

        /// <summary>
        /// Quanlysach control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::LTrWebLibraryBTL.UserControl.BookManageUserControl Quanlysach;
    }
}
